/*
 * ModellerGUIView.java
 */

package swiftmodeller;

import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import java.io.*;
import java.nio.channels.*;
import javax.swing.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

public class SwiftModellerView extends FrameView {

    public SwiftModellerView(SingleFrameApplication app) {
        super(app);
        
        File firstlogin = null;
        File firstpython = null;
        CharSequence cs = "windows";
        firstlogin = new File(userdir + sep + "modpath");

        if(os.contains(cs))
        {
            chkos = 1;
            firstpython = new File(userdir + sep + "pypath");
            if(!firstlogin.exists() || !firstpython.exists())
            {
                new FirstLogin(this.getFrame(), true).setVisible(true);
                new FirstPython(this.getFrame(), true).setVisible(true);
            }
        }
        else
        {
            if(!firstlogin.exists())
            {
                new FirstLogin(this.getFrame(), true).setVisible(true);
            }
        }
        
        if(chkos == 0)
        {
            File es = new File(userdir + sep + "executescript.sh");
            try
            {
                System.gc();
                while(es.exists())
                {
                    es.delete();
                }
                es.createNewFile();
            }
            catch(IOException e)
            {
                new ErrorClose(this.getFrame(), true, "I/O Error");
            }
        }

        DateFormat df = new SimpleDateFormat("EEE, d MMM yyyy HH.mm.ss");
        Date today = Calendar.getInstance().getTime();
        reportdate = df.format(today);
        workpath = new String(userdir + sep + reportdate);
        File dir = new File(workpath);
        dir.mkdir();

        new FlushScript(this.getComponent());
        versionCheck(firstlogin);
        copyResource();
        new ExtractFile("pdb_95.pir.gz", this.getComponent());
        initComponents();
        jButton1.setVisible(false);
        jTextField2.setVisible(false);
        jCheckBox1.setVisible(false);
        jLabel4.setVisible(false);
        jTextField2.setVisible(false);
    }

    /**
	 * 
	 * @return 
	 */
	 /**
	 * This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 * @return 
	 */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        mainPanel.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(swiftmodeller.SwiftModellerApp.class).getContext().getResourceMap(SwiftModellerView.class);
        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(resourceMap.getFont("jTextArea1.font")); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(resourceMap.getFont("jRadioButton1.font")); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(resourceMap.getFont("jRadioButton2.font")); // NOI18N
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);
        jTextField2.setName("jTextField2"); // NOI18N

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(swiftmodeller.SwiftModellerApp.class).getContext().getActionMap(SwiftModellerView.class, this);
        jButton2.setAction(actionMap.get("ProfileSearch")); // NOI18N
        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setToolTipText(resourceMap.getString("jLabel3.toolTipText")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jCheckBox1.setFont(resourceMap.getFont("jCheckBox1.font")); // NOI18N
        jCheckBox1.setText(resourceMap.getString("jCheckBox1.text")); // NOI18N
        jCheckBox1.setName("jCheckBox1"); // NOI18N

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(324, 324, 324)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(378, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(311, 311, 311))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        char abc = evt.getKeyChar();
        if(!(Character.isLetter(abc)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextArea1KeyTyped

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        chkchn++;
        new SelectChain(this.getFrame(), true).setVisible(true);
        jTextField2.setText(SelectChain.template.toString());
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        jButton2.setText("PROCESSING ...");
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {

        if((jTextField1.getText().length() == 0) || (jTextArea1.getText().length() == 0) || (jRadioButton2.isSelected() && count == 0) || (jRadioButton2.isSelected() && chkchn == 0))
        {
            int rVal = jOptionPane1.showConfirmDialog(this.getFrame(), "Information Missing", null, -1, 3);
            if(rVal == jOptionPane1.OK_OPTION)
            {
                jOptionPane1.setVisible(false);
            }
        }
        else
        {
            int chkam = 0;
            for(int i = 0; i < jTextArea1.getText().length(); i++)
            {
                char c = jTextArea1.getText().toUpperCase().charAt(i);
                switch(c)
                {
                    case 'B':
                    case 'J':
                    case 'O':
                    case 'U':
                    case 'X':
                    case 'Z':
                    {
                        chkam++;
                        break;
                    }                        
                }
            }
            if(chkam == 0)
            {
                formSequence();
                if(jRadioButton1.isSelected())
                {
                    searchDatabase();
                    new FlushScript(this.getFrame());
                    new ProfileSearch().setVisible(true);
                }
                else if (jRadioButton2.isSelected())
                {
                    File file = new File(workpath + sep + "Template List.txt");
                    BufferedReader reader = null;
                    StringBuffer contents = new StringBuffer();
                    int i=0;

                    try
                    {
                        reader = new BufferedReader(new FileReader(file));

                        String text = null;
                        while ((text = reader.readLine()) != null)
                        {
                            contents.append(text).append("\n");
                            i++;
                        }
                    }
                    catch (IOException e)
                    {
                        new ErrorClose(this.getFrame(), true, "I/O Error");
                    }
                    finally
                    {
                        try
                        {
                            if (reader != null)
                            {
                                reader.close();
                            }
                        }
                        catch (IOException e)
                        {
                            new ErrorClose(this.getFrame(), true, "I/O Error");
                        }
                    }

                    if((jCheckBox1.isSelected() == false) && (i == 1))
                    {
                        new SUploadAlign(contents, title, this.getComponent());
                        new FlushScript(this.getFrame());
                        suaopfile = SUploadAlign.opfile + ".pap";
                        notalign = 1;
                        new Alignment().setVisible(true);
                    }
                    else if((jCheckBox1.isSelected() == false) && (i > 1))
                    {
                        new MUploadCompare(contents, this.getComponent());
                        new FlushScript(this.getFrame());
                        new Compare().setVisible(true);
                    }
                    else if (jCheckBox1.isSelected() == true)
                    {
                        new MUploadAlign(contents, title, this.getComponent());
                        new FlushScript(this.getFrame());
                        muaopfile = MUploadAlign.muaopfile + ".pap";
                        notalign = 2;
                        new Alignment().setVisible(true);
                    }
                }

                SwiftModellerApp.getApplication().getMainFrame().setVisible(false);
            }
            else
            {
                int rVal = jOptionPane1.showConfirmDialog(this.getFrame(), "Amino Acid Error", null, -1, 3);
                if(rVal == jOptionPane1.OK_OPTION)
                {
                    jOptionPane1.setVisible(false);
                }
            }
        }
    }

    private void versionCheck(File verchk)
    {
        BufferedReader reader = null;
        StringBuffer sb1 = new StringBuffer();
        version = new String();

        try
        {
            reader = new BufferedReader(new FileReader(verchk));

            String text = null;
            while ((text = reader.readLine()) != null)
            {
                sb1.append(text);
            }

            if(chkos == 0)
            {
                version = sb1.substring((sb1.indexOf("modeller") + 8), (sb1.indexOf(sep + "bin")));
            }
            else
            {
                version = sb1.substring((sb1.indexOf("Modeller") + 8), (sb1.indexOf(sep + "bin")));
            }
        }
        catch (IOException e)
        {
            new ErrorClose(this.getFrame(), true, "I/O Error");
        }
        finally
        {
            try
            {
                if (reader != null)
                {
                    reader.close();
                }
            } catch (IOException e)
            {
                new ErrorClose(this.getFrame(), true, "I/O Error");
            }
        }
    }

    private void copyResource()
    {
        StringBuffer path = new StringBuffer(userdir);
        path.append(sep + "resource");

        File resdir = new File(path.toString());
        File desfile = null;

        try
        {
            File[] resfiles = resdir.listFiles();
            for(int i = 0; i < resfiles.length; i++)
            {
                desfile = new File(workpath + sep + resfiles[i].getName());
                if(desfile.exists())
                {
                    desfile.createNewFile();
                }
                FileChannel src = null;
                FileChannel dest = null;
                src = new FileInputStream(resfiles[i]).getChannel();
                dest = new FileOutputStream(desfile).getChannel();
                dest.transferFrom(src, 0, src.size());
                while(desfile.length() != resfiles[i].length())
                {
                    Thread.sleep(1000);
                }
            }
        }
        catch (IOException e)
        {
            new ErrorClose(this.getFrame(), true, "I/O Error");
        }
        catch(InterruptedException e)
        {
            new ErrorClose(this.getFrame(), true, "Thread Interrupted");
        }
    }

    private void Filecopy(ChooseFile file1)
    {
        File desfile = null;

        try
        {
            for(int i = 0; i < file1.file.length; i++)
            {
                desfile = new File(workpath + sep + file1.file[i].getName());
                if(desfile.exists())
                {
                    desfile.createNewFile();
                }
                FileChannel src = null;
                FileChannel dest = null;
                src = new FileInputStream(file1.file[i]).getChannel();
                dest = new FileOutputStream(desfile).getChannel();
                dest.transferFrom(src, 0, src.size());
                while(desfile.length() != file1.file[i].length())
                {
                    Thread.sleep(1000);
                }
            }
        }
        catch (IOException e)
        {
            new ErrorClose(this.getFrame(), true, "I/O Error");
        }
        catch(InterruptedException e)
        {
            new ErrorClose(this.getFrame(), true, "Thread Interrupted");
        }
    }

    private void formSequence()
    {
        title = jTextField1.getText().toUpperCase();
        seqname = title + ".ali";
        String seqpath =  workpath + sep + seqname;
        String seqcontents = ">P1;" + title + "\nsequence:" + title + ":::::::0.00: 0.00\n" + jTextArea1.getText().toUpperCase() + "*";

        File seq = new File(seqpath);
        BufferedWriter writer = null;

        try
        {
            writer = new BufferedWriter(new FileWriter(seq));
            writer.write(seqcontents);
            writer.close();
        }
        catch (IOException e)
        {
            new ErrorClose(this.getFrame(), true, "I/O Error");
        }
    }

    private void searchDatabase()
    {
        File file = new File(workpath + sep + "build_profile.py");
        File outputfile = new File(workpath + sep + "build_profile.log");
        StringBuffer contents = new StringBuffer();
        StringBuffer exectext = new StringBuffer();
        BufferedReader reader = null;
        BufferedWriter writer = null;

        try
        {
            reader = new BufferedReader(new FileReader(file));
            String text = null;
            
            while ((text = reader.readLine()) != null)
            {
                contents.append(text).append("\n");
            }

            contents.replace((contents.indexOf("aln.append(file=") + 16),contents.indexOf(", alignment_format='PIR'"), ("'" + title + ".ali'"));

            writer = new BufferedWriter(new FileWriter(file));
            writer.write(contents.toString());
            writer.close();
        }
        catch (IOException e)
        {
            new ErrorClose(this.getFrame(), true, "I/O Error");
        }
        finally
        {
           try
           {
               if (reader != null)
               {
                   reader.close();
               }
           }
           catch (IOException e)
           {
               new ErrorClose(this.getFrame(), true, "I/O Error");
           }
        }
        
        exectext.append("build_profile.py");
        new ExecuteScript(exectext, outputfile, this.getComponent());
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

        cf = new ChooseFile();
        if(cf.file != null)
        {
            Filecopy(cf);
            StringBuffer templist = new StringBuffer();
            StringBuffer str = new StringBuffer();
            StringBuffer displist = new StringBuffer();
            File templates = new File(workpath + sep + "Template List.txt");
            BufferedReader reader = null;
            BufferedWriter writer = null;

            try
            {
                reader = new BufferedReader(new FileReader(templates));
                String text = null;
                while ((text = reader.readLine()) != null)
                {
                    templist.append(text).append("\n");
                    displist.append(text.substring(0, 8)).append(", ");
                    count++;
                }

                for(int i = 0; i < cf.file.length; i++)
                {
                    String chain = extractchainid(cf.file[i]);
                    if(templist.lastIndexOf(cf.file[i].getName()) == -1)
                    {
                        str.append(cf.file[i].getName()).append(":").append(chain).append("\n");
                        displist.append(cf.file[i].getName()).append(", ");
                        count++;
                    }
                }

                templist.append(str);

                writer = new BufferedWriter(new FileWriter(templates));
                writer.write(templist.toString());
                writer.close();
            }
            catch (IOException e)
            {
                new ErrorClose(this.getFrame(), true, "I/O Error");
            }
            finally
            {
                try
                {
                    if (reader != null)
                    {
                        reader.close();
                    }
                }
                catch (IOException e)
                {
                    new ErrorClose(this.getFrame(), true, "I/O Error");
                }
            }

            displist.substring(0,(displist.length()-2));
            jTextField2.setText(displist.toString());
            jLabel4.setVisible(true);
            if(count > 1)
            {
                jCheckBox1.setVisible(true);
            }
        }
        else
        {
            int rVal = jOptionPane1.showConfirmDialog(this.getFrame(), "Please Select a File", null, -1, 3);
            if(rVal == jOptionPane1.OK_OPTION)
            {
                jOptionPane1.setVisible(false);
            }
        }
    }

    private String extractchainid(File file)
    {
        StringBuffer contents= new StringBuffer();
        BufferedReader reader = null;

        try
        {
            reader = new BufferedReader(new FileReader(file));
            String text = null;

            while ((text = reader.readLine()) != null)
            {
                contents.append(text).append("\n");
            }
        }
        catch (IOException e)
        {
            new ErrorClose(this.getFrame(), true, "I/O Error");
        }
        finally
        {
           try
            {
                if (reader != null)
                {
                    reader.close();
                }
            } catch (IOException e)
            {
                new ErrorClose(this.getFrame(), true, "I/O Error");
            }
        }

        return contents.toString().substring((contents.indexOf("CHAIN: ") + 7), contents.indexOf("\nCOMPND   4")).trim();
    }

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        jButton1.setVisible(true);
        jTextField2.setVisible(true);
    }

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        jCheckBox1.setVisible(false);
        jButton1.setVisible(false);
        jTextField2.setVisible(false);
        jLabel4.setVisible(false);
    }

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {
        char abc = evt.getKeyChar();
        if(!(Character.isLetterOrDigit(abc)))
        {
            evt.consume();
        }
        if(jTextField1.getText().length() >= 5)
        {
            jTextField1.setEditable(false);
            if(abc == 8)
            {
                jTextField1.setEditable(true);
            }
        }    
    }

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {
       jTextArea1.setText("");
    }

    /**
	 * 
	 * @return 
	 */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
    public String reportdate;
    public static String userdir = System.getProperty("user.dir");
    public static String sep = System.getProperty("file.separator");
    public static String workpath;
    public static String title, version;
    public static String suaopfile = new String();
    public static String muaopfile = new String();
    public static int notalign = 0;
    public static int chkos = 0;
    private String seqname;
    private String os = System.getProperty("os.name").toLowerCase();
    private ChooseFile cf;
    private int count = 0;
    private int chkchn = 0;
    private JOptionPane jOptionPane1;
}